# Generated by Django 4.0.7 on 2022-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='chout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
