# Generated by Django 4.0.7 on 2022-10-18 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0008_alter_attendance_chout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='chin',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
