# Generated by Django 4.0.7 on 2022-10-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att_sys', '0009_alter_attendance_chin'),
        ('att_sys', '0009_alter_attendance_chin_alter_attendance_chout'),
    ]

    operations = [
    ]
